##
# Usage: Download and Remove Common Packages
#
# The goal of this script is to download common packages we require, and uninstall packages that would be dangerous to have on the system.
#
# Initially written by a Tired Matthew Harper
##

---
- name: Target Host Facts
  ansible.builtin.setup:

- name: Install Packages on Debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  loop: "{{ deb_install_pkgs }}"

- name: Install Packages on RHEL
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  loop: "{{ rhel_install_pkgs }}"

- name: Install Packages on Alpine
  ansible.builtin.apk:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == 'Alpine'
  loop: "{{ alpine_install_pkgs }}"