---
- name: Install the whois package for mkpasswd
  delegate_to: localhost
  ansible.builtin.package:
    name: whois
    state: present

- name: Generate and hash account passwords
  include_tasks: passwords.yml
  loop: "{{ new_accounts }}"
