---
- name: Generate a random password
  delegate_to: localhost
  ansible.builtin.set_fact:
    pwd: "{{ lookup('password', '/dev/null', length=20, chars='ascii_letters,digits') }}"

- name: Hash password using SHA512 algorithm
  delegate_to: localhost
  ansible.builtin.command: "mkpasswd --method=SHA-512 '{{ pwd }}'"
  register: res
  changed_when: false

- name: Store password and hash in a map
  delegate_to: localhost
  set_fact:
    accounts_map: "{{ accounts_map | default({}) | combine({ item: {'pwd': pwd, 'hash': res.stdout} }) }}"
