---
- name: Ensure Apache is installed
  package:
    name: "{{ apache_service }}"
    state: present

- name: Ensure hardening config directory exists (Debian-based)
  file:
    path: "{{ apache_conf_dir }}/conf-available"
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Ensure headers module is enabled (Debian-based)
  command: a2enmod headers
  when: ansible_os_family == 'Debian'
  notify: Reload apache

- name: Deploy hardening config (Debian-based)
  template:
    src: hardening.conf.j2
    dest: "{{ apache_conf_dir }}/conf-available/zzz-hardening.conf"
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
  notify: Reload apache


- name: Deploy hardening config (RHEL-based)
  template:
    src: hardening.conf.j2
    dest: "{{ apache_conf_dir }}/conf.d/zzz-hardening.conf"
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'RedHat'
  notify: Reload apache

- name: Enable hardening config
  command: a2enconf zzz-hardening
  notify: Reload apache
  when: ansible_os_family == 'Debian'


- name: Ensure Apache is running and enabled
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
