# Set to true to use custom SSL certificates
use_custom_cert: false

# Paths to custom SSL certificate and key
custom_cert_path: "{{ apache_ssl_dir }}/custom.crt"
custom_key_path: "{{ apache_ssl_dir }}/custom.key"

# Domain name for the ServerName directive; defaults to the system's FQDN
server_domain: "{{ ansible_fqdn | default('localhost') }}"

# Apache service and configuration specifics based on OS family
apache_service: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
apache_conf_dir: "{{ '/etc/httpd' if ansible_os_family == 'RedHat' else '/etc/apache2' }}"
apache_ssl_dir: "{{ apache_conf_dir }}/ssl"
apache_conf_d_dir: >-
  {{ '/etc/httpd/conf.d' if ansible_os_family == 'RedHat'
     else '/etc/apache2/sites-available' }}
