---
- name: Check elevation level
  ansible.builtin.win_shell: whoami /groups | findstr "High"

- name: Install IPBan via one-liner
  ansible.windows.win_copy:
    src: installwin2ban.ps1
    dest: C:\Temp\

- name: Verify IPBan exists
  win_stat:
    path: C:\Program Files\IPBan
  register: ipban_program

- debug:
    var: ipban_program.stat.exists


- name: Update IPBan configuration overrides
  win_template:
    src: ipban.override.config.j2
    dest: C:\Program Files\IPBan\ipban.override
  vars:
    # Optional variables – if not set, they are omitted from the generated config.
    ipban_failed_login_attempts: "{{ ipban_failed_login_attempts | default(omit) }}"
    ipban_ip_whitelist: "{{ ipban_ip_whitelist | default(omit) }}"
    ipban_ip_blacklist: "{{ ipban_ip_blacklist | default(omit) }}"
    ipban_ban_time: "{{ ipban_ban_time | default(omit) }}"
    ipban_other_setting: "{{ ipban_other_setting | default(omit) }}"
    
- name: Ensure IPBan service is set to auto and started
  ansible.windows.win_service:
    name: IPBan
    start_mode: auto
    state: started

