##
# Load a config for sysctl
#
# Usage: Setup Basic System Configurations
# Initially written by a Tired Matthew Harper
##

---
  - name: Configure-System
    ansible.builtin.copy:
      src: "{{ conf_name }}"
      dest: "{{ conf_file_trgt }}"
      remote_src: false
      owner: root
      group: root
      mode: '644'
  - name: Load-Config
    ansible.builtin.command: sysctl -p {{ conf_file_trgt }}
    ignore_errors: yes
