---
- name: Install all required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - python3
    - python3-docker
    - python3-pip

- name: Download and execute the Docker install script
  ansible.builtin.shell: | 
    wget -qO- https://get.docker.com | sh

- name: Start and enable the docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
