---
- name: Pull the pihole docker image
  ansible.builtin.docker_image:
    name: pihole/pihole
    tag: latest
    source: pull

- name: Stop and disable the dns service
  ansible.builtin.service:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Update resolv.conf with primary dns
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ primary_dns }}
    owner: root
    group: root
    mode: '0644'

- name: Run the pihole docker container
  ansible.builtin.docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: always
    env:
      TZ: 'America/New_York'
      FTLCONF_webserver_api_password: "{{ pihole_password }}"
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    network_mode: host
