---
- name: Ensure CSV file exists
  ansible.builtin.file:
    path: "{{ output_csv }}"
    state: touch

- name: Rotate passwords for accounts not in whitelist
  ansible.builtin.shell: "echo {{ item }},{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }} >> {{ output_csv }}"
  loop: "{{ accounts }}"
  when: item not in whitelist

- name: Read CSV file and update passwords
  ansible.builtin.command: "some_command_to_update_passwords < {{ output_csv }}"
  args:
    creates: "{{ output_csv }}"