##
# Usage: Log Cron Entries
#
# Initially written by a Tired Matthew Harper
# Modified, tested and verified by Chris Morales - Ubuntu, Debian, RHEL
##

---
  - name: Crontab-Enum
    ansible.builtin.find:
      paths: "{{ item }}"
      recurse: yes
    register: cron_files
    with_items:
      - /var/spool/cron/crontabs
      - /etc/cron.d
    ignore_errors: true

  - name: Concatenate-Output-Path
    ansible.builtin.set_fact:
      combined_output_crontab_paths: "{{ (cron_files.results | map(attribute='files') | sum(start=[]) | map(attribute='path')) }}"

  - name: Generate CronTab Report
    ansible.builtin.shell: |
      printf "\n\n[!] CRONTAB {{ item }} [!]"
      cat {{ item }} 
      printf "\n\n"
    register: cron_report
    with_items:
      - /etc/crontab
      - "{{ combined_output_crontab_paths }}"

  - name: Concatenate-Cron-Report
    ansible.builtin.set_fact:
      combined_output_crontab_results: "{{ (cron_report.results |  map(attribute='stdout') | join('\n')) }}"

  - name: check_report
    ansible.builtin.debug:
      msg: "{{ combined_output_crontab_results }}"
  
  # - name: Ensure the local target directory is made
  #   file:
  #     path: "{{ results_dir }}/cron"
  #     state: directory
  #   delegate_to: localhost

  # - name: Save results to the controller
  #   ansible.builtin.copy:
  #     content: "{{ combined_output_crontab_results }}"
  #     dest: "{{ results_dir }}/cron/{{ ansible_hostname }}-{{ inventory_hostname }}-cron.txt"
  #     mode: '0644'
  #   delegate_to: localhost

  - name: Generate System-Timer-Report
    ansible.builtin.shell: |
      printf "\n[!] System Timers [!]\n"
      systemctl list-timers --all
      printf "\n"
    register: timer_report

  - name: check timer Report
    ansible.builtin.debug:
      msg: "{{ timer_report.stdout_lines }}"

  # - name: Save results to the controller
  #   ansible.builtin.copy:
  #     content: "{{ timer_report.stdout_lines | join('\n') }}"
  #     dest: "{{ results_dir }}/cron/{{ ansible_hostname }}-{{ inventory_hostname }}-system-timers.txt"
  #     mode: '0644'
  #   delegate_to: localhost

  - name: Ensure the local target directory is made
    file:
      path: "{{ results_dir }}/{{ ansible_hostname }}-{{ inventory_hostname }}/cron/"
      state: directory
    delegate_to: localhost

  - name: Save results to the controller
    ansible.builtin.copy:
      content: "{{ combined_output_crontab_results }}"
      #dest: "{{ results_dir }}/services/{{ ansible_hostname }}-{{ inventory_hostname }}-services.txt"
      dest: "{{ results_dir }}/{{ ansible_hostname }}-{{ inventory_hostname }}/cron/{{ timestamp }}-crontab"
      mode: '0644'
    delegate_to: localhost
    retries: 3

  - name: Save results to the controller
    ansible.builtin.copy:
      content: "{{ timer_report.stdout_lines | join('\n') }}"
      #dest: "{{ results_dir }}/services/{{ ansible_hostname }}-{{ inventory_hostname }}-services.txt"
      dest: "{{ results_dir }}/{{ ansible_hostname }}-{{ inventory_hostname }}/cron/{{ timestamp }}-timers"
      mode: '0644'
    delegate_to: localhost
    retries: 3


