---
- name: Install the haproxy package
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Enable and start the haproxy service
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started

- name: Copy the haproxy key file
  ansible.builtin.copy:
    src: "{{ key_path }}"
    dest: "/root/{{ key_path | basename }}"
    mode: '0600'
  when: use_tls

- name: Copy the haproxy config file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart haproxy service
