##
# Configure auditd on the target system.
#
# Initially written by a Tired Matthew Harper
##

---
- name: Configure Forward Journald to Syslog
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '.*ForwardToSyslog.*'
    line: 'ForwardToSyslog=yes'

- name: Configure Compress Journald Logs
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '.*Compress.*'
    line: 'Compress=yes'

- name: Configure Persistent Storage for Journald
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '.*Storage.*'
    line: 'Storage=persistent'