---
- name: Get accounts with existing password hashes
  ansible.builtin.shell: |
    awk -F: '($2 !~ /^[!*]/ && $2 != "") { print $1 }' /etc/shadow
  register: user_accounts
  changed_when: false

- name: Save accounts list as a fact
  ansible.builtin.set_fact:
    accounts: "{{ user_accounts.stdout_lines }}"
