---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  loop: "{{ accounts }}"

- name: Add public key to authorized keys file
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.ssh/authorized_keys"
    line: "{{ lookup('file', 'files/key.pub') }}"
    create: yes
    state: present
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop: "{{ accounts }}"
