##
# Usage: Print and gather the process tree of the system
#
# Initially written by a Tired Matthew Harper
# Modified, tested and verified by Chris Morales - Ubuntu, Debian, RHEL
##

---
  - name: Install pstree
    ansible.builtin.package:
      name: psmisc
      state: present
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  # - name: Locate-Danger-Sudo
  - name: Gather processes and process trees
    ansible.builtin.shell: |
      printf "[!] ps [!]\n"
      ps -auxfww
      printf "\n\n\n\n\n"
      printf "[!] pstree [!]\n"
      pstree -plas
    register: process_list
    ignore_errors: true

  # - name: Ensure the local target directory is made
  #   file:
  #     path: "{{ results_dir }}/processes"
  #     state: directory
  #   delegate_to: localhost

  # - name: Save results to the controller
  #   ansible.builtin.copy:
  #     content: "{{ process_list.stdout }}"
  #     dest: "{{ results_dir }}/processes/{{ ansible_hostname }}-{{ inventory_hostname }}-processes.txt"
  #     mode: '0644'
  #   delegate_to: localhost


  - name: Ensure the local target directory is made
    file:
      path: "{{ results_dir }}/{{ ansible_hostname }}-{{ inventory_hostname }}/processes/"
      state: directory
    delegate_to: localhost

  - name: Save results to the controller
    ansible.builtin.copy:
      content: "{{ process_list.stdout }}"
      #dest: "{{ results_dir }}/services/{{ ansible_hostname }}-{{ inventory_hostname }}-services.txt"
      dest: "{{ results_dir }}/{{ ansible_hostname }}-{{ inventory_hostname }}/processes/{{ timestamp }}"
      mode: '0644'
    delegate_to: localhost
    retries: 3