##
# Usage: Setup basic file Permissions
#
# Initially written by a Tired Matthew Harper
##

---
- name: Configure Passwd and Group Files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '644'
    state: file
  with_items:
    - /etc/passwd
    - /etc/group
    - /etc/passwd-
    - /etc/group-
  ignore_errors: true

- name: Configure Shadow Files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: shadow
    mode: '640'
    state: file
  with_items:
    - /etc/shadow
    - /etc/gshadow
    - /etc/shadow-
    - /etc/gshadow-
  ignore_errors: true

- name: Configure Cron Directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '755'
    state: directory
  with_items:
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly
    - /etc/cron.hourly
  ignore_errors: true

- name: Configure Crontab
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '755'
    state: file
  ignore_errors: true

- name: Configure Notice Files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '744'
    state: file
  with_items:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net
  ignore_errors: true

- name: Find SSH Files
  ansible.builtin.find:
    paths: /etc/ssh
    recurse: yes
    file_type: file
  register: ssh_files

- name: Configure SSHD Permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '644'
    state: file
  with_items: "{{ ssh_files.files }}"
  when: not item.path.endswith('_key')
  ignore_errors: true