---
- name: Install wireshark
  ansible.windows.win_copy:
    src: install_wireshark.ps1
    dest: C:\Temp\

- name: Run wireshark install script
  ansible.windows.win_shell: |
    PowerShell.exe -ExecutionPolicy Bypass -File "C:\Temp\install_wireshark.ps1"


- name: Install nmap
  ansible.windows.win_copy:
    src: install_nmap.ps1
    dest: C:\Temp\

- name: Run Fnmap install script
  ansible.windows.win_shell: |
    PowerShell.exe -ExecutionPolicy Bypass -File "C:\Temp\install_nmap.ps1"


- name: Install sysinternals
  ansible.windows.win_copy:
    src: install_sysinternals.ps1
    dest: C:\Temp\

- name: Run sysinternals install script
  ansible.windows.win_shell: |
    PowerShell.exe -ExecutionPolicy Bypass -File "C:\Temp\install_sysinternals.ps1"



- name: Install firefox
  ansible.windows.win_copy:
    src: install_firefox.ps1
    dest: C:\Temp\

- name: Run Firefox install script
  ansible.windows.win_shell: |
    PowerShell.exe -ExecutionPolicy Bypass -File "C:\Temp\install_firefox.ps1"

  