apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-volume
  labels:
    type: local
  namespace: homelab
spec:
  claimRef:
    namespace: homelab
    name: pihole-etc-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pihole/etc"