apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-volume
  labels:
    type: local
  namespace: homelab
spec:
  claimRef:
    namespace: homelab
    name: pihole-dnsmasq-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pihole/dnsmasq.d"