apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-claim
  namespace: homelab
spec:
  volumeName: pihole-etc-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi