---
- name: Install Apache + OpenSSL on Debian-based
  package:
    name:
      - apache2
      - openssl
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Apache + mod_ssl + OpenSSL on RHEL-based
  package:
    name:
      - httpd
      - mod_ssl
      - openssl
    state: present
  when: ansible_os_family == 'RedHat'

- name: Enable SSL module (Debian-based)
  command: a2enmod ssl
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Ensure SSL certificate directory exists
  file:
    path: "{{ apache_ssl_dir }}"
    state: directory
    mode: '0755'

- name: Generate self-signed certificate if custom cert is not provided
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout {{ apache_ssl_dir }}/apache-selfsigned.key
    -out {{ apache_ssl_dir }}/apache-selfsigned.crt
    -subj "/CN={{ server_domain }}"
  args:
    creates: "{{ apache_ssl_dir }}/apache-selfsigned.crt"
  when: not use_custom_cert

- name: Deploy SSL configuration
  template:
    src: ssl.conf.j2
    dest: "{{ apache_conf_d_dir }}/ssl.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Deploy HTTP to HTTPS redirect configuration
  template:
    src: redirect.conf.j2
    dest: "{{ apache_conf_d_dir }}/redirect.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Enable redirect site (Debian-based)
  command: a2ensite redirect
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Ensure Apache is running and enabled
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
