 tasks:
    - name: Create temporary folder for GPO backup on the domain controller
      win_file:
        path: "{{ gpo_backup_destination }}"
        state: directory

    - name: Copy GPO backup from control machine to domain controller
      win_copy:
        src: "{{ gpo_backup_source }}"
        dest: "{{ gpo_backup_destination }}"
      

    - name: Import the GPO backup onto the domain controller
      win_shell: |
        Import-GPO -BackupGpoName "{{ gpo_name }}" -Path "{{ gpo_backup_destination }}" -TargetName "{{ gpo_name }}" -CreateIfNeeded
      args:
        executable: powershell

    - name: Force a Group Policy update on the domain controller
      win_shell: gpupdate /force