##
# Usage: Stop Potentially Dangerous Services
#
# Initially written by a Tired Matthew Harper
##

---

  - name: Disable-Services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: "{{ State }}"
      masked: "{{ Is_Masked }}"
    ignore_errors: true
    loop: "{{ services_to_stop }}"
