---
- name: Install EPEL repo on RHEL
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install sshguard
  ansible.builtin.package:
    name: sshguard
    state: present

- name: Enable and start sshguard service
  ansible.builtin.service:
    name: sshguard
    enabled: true
    state: started

- name: Copy sshguard whitelist file
  ansible.builtin.copy:
    src: whitelist
    dest: /etc/sshguard/whitelist
    owner: root
    group: root
    mode: '0644'
  notify: Restart sshguard service
